import { Roboto } from 'next/font/google'
import './globals.css'
import Navbarone from './Essentials/Navbarone'
import Footer from './Essentials/Footer'
import AboveFooter from './Essentials/AboveFooter'


const inter = Roboto({
  subsets: ['latin'],
  weight: '500'
})

export const metadata = {
  title: 'M-Zone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    </head>
    <body className={inter.className}>
      {children}
      <AboveFooter/>
      <Footer/>
      <script src="./script.js"></script>
    </body>
  </html>
  )
}
